name: test_gemma3n_flutter
description: Educational AI Assistant with Gemma 3n and robust Flutter architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Your existing dependencies
  permission_handler: ^11.1.0
  path_provider: ^2.1.1

  # State Management
  flutter_riverpod: ^2.4.9

  # Navigation (for later)
  go_router: ^12.1.3

  # UI Components
  cupertino_icons: ^1.0.6

  # HTTP & Networking (for future API calls)
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Logging
  logger: ^2.0.2+1

  # Error Handling & Crash Reporting (optional)
  # sentry_flutter: ^7.14.0

  # Utilities
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Device Info
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

  # Voice-to-Voice Interface
  record: ^5.0.4                    # Audio recording
  speech_to_text: ^7.1.0            # STT with offline support
  flutter_tts: ^4.0.2               # TTS with offline support
  audioplayers: ^6.0.0              # Audio playback

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.1

  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  # Remove assets section for now - add back when you create the folders
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Remove fonts section for now - using system fonts
  # fonts:
  #   - family: Roboto

dependency_overrides:
  # Pin record_platform_interface below 1.3.0 until record_linux plugin implements startStream
  record_platform_interface: ">=1.2.0 <1.3.0"
