name: Build Flutter Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true

    - name: Clean Flutter project
      run: |
        flutter clean
        flutter pub get
        flutter pub deps

    - name: Analyze Flutter code (continue on error)
      run: flutter analyze --no-fatal-infos
      continue-on-error: true

    - name: Run Flutter tests (continue on error)
      run: flutter test
      continue-on-error: true

    - name: Create keystore for signing (optional)
      run: |
        if [ ! -f android/app/key.jks ]; then
          keytool -genkey -v -keystore android/app/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias release \
            -dname "CN=Flutter Demo, OU=Flutter, O=Demo, L=Demo, S=Demo, C=US" \
            -storepass flutter123 -keypass flutter123
        fi

    - name: Create key.properties
      run: |
        echo "storePassword=flutter123" > android/key.properties
        echo "keyPassword=flutter123" >> android/key.properties
        echo "keyAlias=release" >> android/key.properties
        echo "storeFile=key.jks" >> android/key.properties

    - name: Build APK (Debug) - Skip analyze errors
      run: flutter build apk --debug --no-analyze

    - name: Build APK (Release) - Skip analyze errors  
      run: flutter build apk --release --no-analyze

    - name: Build App Bundle (Release) - Skip analyze errors
      run: flutter build appbundle --release --no-analyze

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 30

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 30

    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
